// app/layout.js
import { Playfair_Display, Lato } from "next/font/google";
import "./globals.css";
import TopHeader from "./components/Layout/Header";
import Footer from "./components/Footer/Footer";
import { ConfigProvider } from "antd";
import Providers from "./providers";

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  display: "swap",
});

export const metadata = {
  title: "Two-Gooders",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${playfair.variable} ${lato.variable}`}>
        <Providers>
          <ConfigProvider
            theme={{
              token: {
                fontFamily: "var(--font-lato)",
              },
              components: {
                Table: {
                  borderRadius: 0,
                  headerBorderRadius: 0,
                },
                Typography: {
                  fontFamily: "var(--font-playfair)",
                },
                Menu: {
                  fontFamily: "var(--font-lato)",
                },
                Button: {
                  fontFamily: "var(--font-lato)",
                  borderRadius: 0
                },
                Input: {
                  borderRadius: 0
                }
              },
            }}
          >
            <TopHeader />
            <main>{children}</main>
            <Footer />
          </ConfigProvider>
        </Providers>
      </body>
    </html>
  );
}
